- name: Setup Redis YUM repos
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: Update IP address in config /etc/redis.conf file
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update IP address in /etc/redis/redis.conf config file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name:  Enable and Start Redis service
  ansible.builtin.systemd:
    name:  redis
    state:  restarted
    enabled:  yes
    daemon-reload:  yes
