- name: Configure YUM repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ
  ansible.builtin.yum:
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
      - rabbitmq-server

- name: Start and enable RabbitMQ
  ansible.builtin.systemd:
    name: rabbitmq-server
    enabled: yes
    state: restarted

- name: Create Application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present