- name: Configure MySQL repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed

- name:  Enable and Start MySQL service
  ansible.builtin.systemd:
    name:  mysqld
    state:  restarted
    enabled:  yes
    daemon-reload:  yes

- name: Check the DB password by collecting the info
  community.mysql.mysql_info:
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_status

- name: Resetting password
  when: mysql_status.failed
  block:
    - name: Grep MySQL Default pasword
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: DEFAULT_ROOT_PASSWORD

    - name: Copy password reset file
      ansible.builtin.copy:
        src: rootpass.sql
        dest: /tmp/rootpass.sql

    - name: Resetting MySQL password
      ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_ROOT_PASSWORD.stdout}}" </tmp/rootpass.sql

- name: Check the validate password plugin
  ansible.builtin.shell: echo show plugins | mysql -uroot -pRoboShop@1 | grep validate_password
  register: plugin_stat
  ignore_errors: yes

- name: Uninstall validate password plugin
  when: plugin_stat.rc == 0
  block:
    - name: Copy SQL file to uninstall plugin
      ansible.builtin.copy:
        src: pass-validate.sql
        dest: /tmp/pass-validate.sql

    - name: Uninstall plugin
      ansible.builtin.shell: mysql --connect-expired-password -uroot -pRoboShop@1 </tmp/pass-validate.sql

- name: Download and Extract {{COMPONENT}}
  include_role:
    name: common
    tasks_from: download

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: RoboShop@1