
#1. Add roboshop User
#
#```bash
#  # useradd roboshop
#```
#
#1. Switch to roboshop user and perform the following commands.
#
#```bash
#$ curl -L -s -o /tmp/dispatch.zip https://github.com/roboshop-devops-project/dispatch/archive/refs/heads/main.zip
#$ unzip /tmp/dispatch.zip
#$ mv dispatch-main dispatch
#$ cd dispatch
#$ go mod init dispatch
#$ go get
#$ go build
#```
#
#1. Update the systemd file and configure the dispatch service in systemd

- name: Install GoLang
  ansible.builtin.yum:
    name: golang

- name: Setup Application user, Download and Extract {{COMPONENT}} component
  include_role:
    name: common
    tasks_from: download

- name: Configure go module
  ansible.builtin.shell: go mod init dispatch && go get && go build

- name: SystemD configuration setup
  include_role:
    name: common
    tasks_from: systemd