- name:  Configure YUM repos
  ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name:  Install NodeJs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state:  installed

- name: Add Roboshop user
  ansible.builtin.user:
    name: roboshop
    comment:  Roboshop application user

- name:  Download and Extract file
  include_role:
    name:  common
    tasks_from:  download

- name:  Clean up old content
  ansible.builtin.file:
    path:  /home/roboshop/catalogue
    state:  absent

- name:  Copy content
  ansible.builtin.copy:
    src:  /tmp/catalogue-main/
    dest:  /home/roboshop/catalogue/
    remote_src:  yes


- name:  Install NodeJs dependencies.
  community.general.npm:
    path:  /home/roboshop/catalogue

- name:  Replace MONGO_DNSNAME in the systemd configuration file
  ansible.builtin.replace:
    path:  /home/roboshop/catalogue/systemd.service
    regexp:  'MONGO_DNSNAME'
    replace:  'mongodb.roboshop.internal'

- name:  Copy SystemD file
  ansible.builtin.copy:
    src:  /home/roboshop/catalogue/systemd.service
    dest:  /etc/systemd/system/catalogue.service

- name:  Enable and Start Catalogue service
  ansible.builtin.systemd:
    name:  catalogue
    state:  restarted
    enabled:  yes
    daemon-reload:  yes
