
#```bash
#  # useradd roboshop
#
#```
#
#1. So let's switch to the `roboshop` user and run the following commands.
#
#```bash
#$ curl -s -L -o /tmp/catalogue.zip "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
#$ cd /home/roboshop
#$ unzip /tmp/catalogue.zip
#$ mv catalogue-main catalogue
#$ cd /home/roboshop/catalogue
#$ npm install
#
#```
#
#1. Update SystemD file with correct IP addresses
#
#Update `MONGO_DNSNAME` with MongoDB Server IP
#
#2. Now, lets set up the service with systemctl.
#
#```bash
#  # mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service
#  # systemctl daemon-reload
#  # systemctl start catalogue
#  # systemctl enable catalogue
#
#```

- name:  Configure YUM repos
  ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name:  Install NodeJs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state:  installed

- name: Add Roboshop user
  ansible.builtin.user:
    name: Roboshop
    comment:  Roboshop application user

- name: Switch to Roboshop user
  become: true
  become_user: Roboshop


#- name:  Enable and Start Catalogue service
#  ansible.builtin.systemd:
#    name:  catalogue
#    state:  restarted
#    enabled:  yes
#    daemon-reload:  yes