- name:  Install Maven
  ansible.builtin.yum:
    name: maven
    state:  installed

- name:  Setup App user, Download and Extract {{COMPONENT}} content
  include_role:
    name:  common
    tasks_from:  download


- name:  Maven packaging
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}/


- name:  SystemD configuration setup
  include_role:
      name:  common
      tasks_from:  systemd
